# Generated by Django 2.1.4 on 2019-01-10 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('isFav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_image',
            fields=[
                ('tbl_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloud.tbl_file')),
                ('resolution', models.IntegerField()),
            ],
            bases=('cloud.tbl_file',),
        ),
        migrations.CreateModel(
            name='tbl_music',
            fields=[
                ('tbl_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloud.tbl_file')),
                ('time', models.IntegerField()),
                ('artist', models.CharField(max_length=50)),
                ('mType', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
            ],
            bases=('cloud.tbl_file',),
        ),
        migrations.CreateModel(
            name='tbl_video',
            fields=[
                ('tbl_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cloud.tbl_file')),
                ('vType', models.CharField(max_length=50)),
                ('resolution', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            bases=('cloud.tbl_file',),
        ),
        migrations.AddField(
            model_name='tbl_file',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user'),
        ),
    ]
