# Generated by Django 2.1.4 on 2019-01-10 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20190110_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('describtion', models.CharField(max_length=200)),
                ('isFav', models.BooleanField(default=False)),
                ('children_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud.tbl_folder')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cloud.tbl_folder')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_folder_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_file')),
                ('folder_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_folder')),
            ],
        ),
    ]
