# Generated by Django 2.1.4 on 2019-01-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_tbl_folder_tbl_folder_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adType', models.CharField(max_length=50)),
                ('extAddress', models.CharField(max_length=500)),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user')),
            ],
        ),
    ]
