# Generated by Django 2.1.4 on 2019-01-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_tbl_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Please fill with a maximum 12-digit phone number', max_length=12)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('from_next_cloud_or_another', models.BooleanField(default=False)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user', verbose_name='Contact User:')),
            ],
        ),
    ]
