# Generated by Django 2.1.4 on 2019-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_tbl_share_with_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_external_user',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
            ],
        ),
    ]
