# Generated by Django 2.1.4 on 2019-01-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0010_tbl_share_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_groups_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user')),
            ],
        ),
    ]
