# Generated by Django 2.1.4 on 2019-01-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0011_tbl_groups_tbl_groups_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_folder',
            name='children_id',
        ),
        migrations.RemoveField(
            model_name='tbl_folder',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='tbl_folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbl_folder', to='cloud.tbl_folder'),
        ),
        migrations.AlterField(
            model_name='tbl_folder',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user', verbose_name='Owner'),
        ),
    ]
