# Generated by Django 2.1.4 on 2019-01-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_auto_20190112_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_image',
            name='image_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_image',
            name='tbl_file_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cloud.tbl_file'),
        ),
    ]
