# Generated by Django 2.1.4 on 2019-01-13 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_auto_20190113_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_share_with_user',
            name='user_id2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloud.tbl_user', verbose_name='Shared User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_share_with_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cloud.tbl_user', verbose_name='User Name'),
        ),
    ]
